### ISSUE TITLE
Touch command conflict: two finger single tap cannot be used to stop speech with add-on 23.06

### ISSUE THREAD

**Issue by josephsl** [josephsl/enhancedTouchGestures#1]
Hi,

Looks like a command conflict was introduced with Enhanced Touch Gestures 23.06:

Steps to reproduce:

1. Instlal Enhanced Touch Gestures 23.06 and restart NVDA.
2. Try reading a long passage.
3. Perform a two finger single tap.

Expected: speech stops.
Actual: NVDA steps through audio ducking settings.
Cause: two finger single tap is defined as stop speech (control key) in NVDA, whereas it is overridden in Enhanced Touch Gestures 23.06 to toggle audio ducking (NVDA+Shift+D).
Ideal solution: plesae reassign something else to audio ducking toggle and try minimizing conflicts with NVDA Core commands if possible.

Thanks.

**Comment by kefaslungu** [comment]
fix by 23.06.1
